spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/winkproject
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: MvvN2JWVkz6iXqdd0ON9nITywmqx0SKQ
            redirect_uri: http://localhost:8080/auth/callback
  jwt:
    secret: dSJjrMGIIS57olGcpZOjwGkAXcqrXdM4

springdoc:
  swagger-ui:
    operations-sorter: default
    tags-sorter: alpha